# Generated by Django 4.2.30 on 2026-07-24 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('section', models.CharField(default='A', max_length=5)),
                ('year', models.IntegerField(default=4)),
                ('cgpa', models.FloatField(default=0.0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('placement_status', models.CharField(choices=[('PLACED', 'Placed'), ('UNPLACED', 'Unplaced'), ('IN_PROCESS', 'In Process'), ('NOT_INTERESTED', 'Not Interested')], default='UNPLACED', max_length=20)),
                ('arrears_count', models.IntegerField(default=0)),
                ('resume_link', models.URLField(blank=True, max_length=500, null=True)),
                ('github_link', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.department')),
            ],
            options={
                'ordering': ['roll_number'],
            },
        ),
    ]
