# Generated by Django 4.2.30 on 2026-07-24 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('STUDENTS_ABOVE_80', 'Students Scoring >80%'), ('STUDENTS_BELOW_40', 'Students Scoring <40%'), ('INTERVIEW_ELIGIBLE', 'Interview Eligible Students'), ('ABSENT_STUDENTS', 'Absent Students Report'), ('DEPARTMENT_WISE', 'Department-wise Report'), ('ASSESSMENT_WISE', 'Assessment-wise Report'), ('TOP_20', 'Top 20 Performers Report'), ('COMPANY_ELIGIBILITY', 'Company Eligibility Report')], max_length=50)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('file_format', models.CharField(default='PDF', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
