# Generated by Django 4.2.30 on 2026-07-24 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_roles', models.CharField(default='Software Engineer', max_length=255)),
                ('visiting_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cgpa', models.FloatField(default=7.0)),
                ('max_arrears', models.IntegerField(default=0)),
                ('min_coding_score', models.FloatField(default=60.0)),
                ('min_aptitude_score', models.FloatField(default=60.0)),
                ('min_communication_score', models.FloatField(default=50.0)),
                ('min_overall_avg', models.FloatField(default=65.0)),
                ('allowed_departments', models.TextField(default='ALL', help_text='Comma separated dept codes or ALL')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='company_eligibility.company')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(default=False)),
                ('details', models.JSONField(default=dict)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_results', to='company_eligibility.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_eligibilities', to='students.student')),
            ],
            options={
                'unique_together': {('company', 'student')},
            },
        ),
    ]
