# Generated by Django 4.2.30 on 2026-07-24 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('APTITUDE', 'Aptitude'), ('CODING', 'Coding'), ('TECHNICAL_MCQ', 'Technical MCQ'), ('SQL', 'SQL'), ('COMMUNICATION', 'Communication'), ('MOCK_INTERVIEW', 'Mock Interview'), ('GROUP_DISCUSSION', 'Group Discussion'), ('RESUME_REVIEW', 'Resume Review')], default='APTITUDE', max_length=30)),
                ('date', models.DateField()),
                ('max_marks', models.FloatField(default=100.0)),
                ('duration_minutes', models.IntegerField(default=90)),
                ('weightage_percent', models.FloatField(default=15.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
